---
component_readiness:
  - name: 4.18-main
    base_release:
      release: "4.17"
      relative_start: ga-30d
      relative_end: ga
    sample_release:
      release: "4.18"
      relative_start: now-7d
      relative_end: now
    variant_options:
      column_group_by:
        Architecture: {}
        Network: {}
        Platform: {}
      db_group_by:
        Architecture: {}
        FeatureSet: {}
        Installer: {}
        Network: {}
        Platform: {}
        Suite: {}
        Topology: {}
        Upgrade: {}
      include_variants:
        Architecture:
          - amd64
        FeatureSet:
          - default
        Installer:
          - ipi
          - upi
        Owner:
          - eng
        Platform:
          - aws
          - azure
          - gcp
          - metal
          - vsphere
        Topology:
          - ha
        CGroupMode:
          - v2
        ContainerRuntime:
          - runc
    advanced_options:
      minimum_failure: 3
      confidence: 95
      pity_factor: 5
      ignore_missing: false
      ignore_disruption: true
      pass_rate_required_new_tests: 95
    metrics:
      enabled: true
    regression_tracking:
      enabled: true
  - name: 4.18-pass-rate-95
    base_release:
      release: "4.17"
      relative_start: now-30d
      relative_end: now
    sample_release:
      release: "4.18"
      relative_start: now-7d
      relative_end: now
    variant_options:
      column_group_by:
        Architecture: {}
        Network: {}
        Platform: {}
      db_group_by:
        Architecture: {}
        FeatureSet: {}
        Installer: {}
        Network: {}
        Platform: {}
        Suite: {}
        Topology: {}
        Upgrade: {}
      include_variants:
        Architecture:
          - amd64
        FeatureSet:
          - default
        Installer:
          - ipi
          - upi
        Owner:
          - eng
        Platform:
          - aws
          - azure
          - gcp
          - metal
          - vsphere
        Topology:
          - ha
    advanced_options:
      minimum_failure: 3
      pass_rate_required_new_tests: 95
      pass_rate_required_all_tests: 80
  - name: 4.18-ha-vs-single
    base_release:
      release: "4.18"
      relative_start: now-7d
      relative_end: now
    sample_release:
      release: "4.18"
      relative_start: now-7d
      relative_end: now
    variant_options:
      column_group_by:
        Architecture: {}
        Network: {}
        Platform: {}
      db_group_by:
        Architecture: {}
        FeatureSet: {}
        Installer: {}
        Network: {}
        Platform: {}
        Suite: {}
        Upgrade: {}
      include_variants:
        Architecture:
          - amd64
        FeatureSet:
          - default
        Installer:
          - ipi
          - upi
        Owner:
          - eng
        Platform:
          - aws
          - azure
          - gcp
          - metal
          - vsphere
        Topology:
          - ha
        CGroupMode:
          - v2
        ContainerRuntime:
          - runc
      compare_variants:
        Topology:
          - single
      variant_cross_compare:
        - Topology
    advanced_options:
      minimum_failure: 3
      confidence: 95
      pity_factor: 5
      ignore_missing: false
      ignore_disruption: true
    metrics:
      enabled: false
    regression_tracking:
      enabled: false
  - name: 4.18-runc-vs-crun
    base_release:
      release: "4.18"
      relative_start: now-7d
      relative_end: now
    sample_release:
      release: "4.18"
      relative_start: now-7d
      relative_end: now
    variant_options:
      column_group_by:
        Architecture: {}
        Network: {}
        Platform: {}
      db_group_by:
        Architecture: {}
        FeatureSet: {}
        Installer: {}
        Network: {}
        Platform: {}
        Suite: {}
        Topology: {}
        Upgrade: {}
      include_variants:
        Architecture:
          - amd64
        FeatureSet:
          - default
        Installer:
          - ipi
          - upi
        Owner:
          - eng
        Platform:
          - aws
          - azure
          - gcp
          - metal
          - vsphere
        Topology:
          - ha
        CGroupMode:
          - v2
        ContainerRuntime:
          - runc
      compare_variants:
        ContainerRuntime:
          - crun
      variant_cross_compare:
        - ContainerRuntime
    advanced_options:
      minimum_failure: 3
      confidence: 95
      pity_factor: 5
      ignore_missing: false
      ignore_disruption: true
    metrics:
      enabled: false
    regression_tracking:
      enabled: false
  - name: 4.17-main
    base_release:
        release: "4.16"
        relative_start: ga-30d
        relative_end: ga
    sample_release:
        release: "4.17"
        relative_start: now-7d
        relative_end: now
    variant_options:
        column_group_by:
            Architecture: {}
            Network: {}
            Platform: {}
        db_group_by:
            Architecture: {}
            FeatureSet: {}
            Installer: {}
            Network: {}
            Platform: {}
            Suite: {}
            Topology: {}
            Upgrade: {}
        include_variants:
            Architecture:
                - amd64
            FeatureSet:
                - default
            Installer:
                - ipi
                - upi
            Owner:
                - eng
            Platform:
                - aws
                - azure
                - gcp
                - metal
                - vsphere
            Topology:
                - ha
            CGroupMode:
                - v2
            ContainerRuntime:
                - runc
    advanced_options:
        minimum_failure: 3
        confidence: 95
        pity_factor: 5
        ignore_missing: false
        ignore_disruption: true
    metrics:
      enabled: true
    regression_tracking:
      enabled: true
  - name: 4.16-main
    base_release:
      release: "4.15"
      relative_start: ga-30d
      relative_end: ga
    sample_release:
      release: "4.16"
      relative_start: now-7d
      relative_end: now
    variant_options:
      column_group_by:
        Architecture: {}
        Network: {}
        Platform: {}
      db_group_by:
        Architecture: {}
        FeatureSet: {}
        Installer: {}
        Network: {}
        Platform: {}
        Suite: {}
        Topology: {}
        Upgrade: {}
      include_variants:
        Architecture:
          - amd64
        FeatureSet:
          - default
        Installer:
          - ipi
          - upi
        Owner:
          - eng
        Platform:
          - aws
          - azure
          - gcp
          - metal
          - vsphere
        Topology:
          - ha
        CGroupMode:
          - v2
        ContainerRuntime:
          - runc
    advanced_options:
      minimum_failure: 3
      confidence: 95
      pity_factor: 5
      ignore_missing: false
      ignore_disruption: true
    metrics:
      enabled: true
    regression_tracking:
      enabled: true
